from django.conf.urls import include, url
from campaigns.yiquan import Views_Action, Views_Page

urlpatterns = [
    url(r'^pc-index.html', Views_Page.pc_page_index),
    url(r'^pc-news.html', Views_Page.pc_page_news),
    url(r'^pc-product.html', Views_Page.pc_page_product),
    url(r'^mobile/wx-index.html',  Views_Page.mobile_page_index),
    url(r'^wx-activeIndex.html', Views_Page.mobile_page_activeIndex),
    url(r'^wx-index2.html', Views_Page.mobile_page_index2),
    url(r'^wx-make.html', Views_Page.mobile_page_make),
    url(r'^wx-makeSuccess.html', Views_Page.mobile_page_makeSuccess),
    url(r'^wx-mark.html', Views_Page.mobile_page_mark),
    url(r'^wx-myProduct.html', Views_Page.mobile_page_myproduct),
    url(r'^wx-nav.html', Views_Page.mobile_page_nav),
    url(r'^wx-otherProduct.html', Views_Page.mobile_page_other),
    url(r'^wx-product.html', Views_Page.mobile_page_product),
    url(r'^wx-tidbits.html', Views_Page.mobile_page_tidbits),
    url(r'^wx-weMake.html', Views_Page.mobile_page_wemake),
    url(r'^wx-weMakeSeed.html', Views_Page.mobile_page_makeseed),
    url(r'^wx-weMakeShare.html', Views_Page.mobile_page_share),
    url(r'^wx-weMakeShare1.html', Views_Page.mobile_page_Share),
    url(r'^wx-weMakeShareEnd.html', Views_Page.mobile_page_ShareEnd),
    url(r'^fetchWorks', Views_Action.pc_fetch_works),
    url(r'^vote', Views_Action.pc_vote),
    url(r'^workidfetch', Views_Action.Workidfetchworks),
    url(r'^uploadwork', Views_Action.single_upload_work_fix),
    url(r'^openid', Views_Action.openid),
    url(r'^testfetchwork', Views_Action.openidfetchs),
    url(r'^uploadShareWork', Views_Action.shareupload),
    url(r'^sharefetch', Views_Action.workidfetchwork),
    url(r'^searchwork', Views_Action.searchwork),
    url(r'^mobile/index.html', Views_Page.mobile_page_index),
    url(r'^fetchwork', Views_Action.pc_fetch_work),
    url(r'^getSignPackage', Views_Action.get_sign_package),
    url(r'^myfetch', Views_Action.myfetchworks),
    url(r'^finishWork', Views_Action.finishWork),
    url(r'^test', Views_Page.auth_test),
    url(r'^fetch_front_image$', Views_Action.fetch_front_image_func),
    url(r'^fetch_back_image$', Views_Action.fetch_back_image_func),
    url(r'^vescount$', Views_Action.vescount),
    url(r'^workcount$', Views_Action.workaddcount),
    url(r'^wx-infinite.html$', Views_Page.shuazuoping)
]