"""
Django settings for cmp project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9y(sg8a^!mo7cn#1bk$qx237z!w$emg6=4ne$c6zp00agrt680'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django.contrib.staticfiles',
    'campaigns.foundation',
    'campaigns.fenda201605',
    'campaigns.yiquan',
    'campaigns.lottery',
    'DjangoUeditor',
    'campaigns.management',
    'campaigns.testproject',
    'campaigns.nihuawocai',
    'campaigns.qiche',
    'campaigns.yh',
    'campaigns.picc'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'dwebsocket.middleware.WebSocketMiddleware'
)


ROOT_URLCONF = 'cmp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cmp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'cmp',
#         'USER': 'postgres',
#         'PASSWORD': 'Hytestsql',
#         'HOST': '192.168.100.250',
#         'PORT': '5432'
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'test',
        'USER': 'postgres',
        'PASSWORD': 'Hytestsql',
        'HOST': '192.168.100.250',
        'PORT': '5432'
    }
}
CACHES = {
    'default': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': '127.0.0.1:6379',
        'OPTIONS': {
            "CLITEN_CLASS": "redis_cache.client.DefaultClient"
        },
    },
}

REDIS_TIMEOUT = 7*27*60*60
CUBES_REDIS_TIMEOUT = 60*60
NEVER_REDIS_TIMEOUT = 365*24*60*60
ACCESS_TIMEOUT = 60*60
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# region CDN
# STATIC_URL = 'http://cdn.com/static/'
# MEDIA_URL = 'http://cdn.com/media/'
# end region

TINYMCE_DEFAULT_CONFIG = {  
'theme': 'advanced',   
'theme_advanced_toolbar_location' : 'top',  
'theme_advanced_toolbar_align' : 'left',   
'width': 600,  
'height': 400,  
}

# region local
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
# end region

STATIC_ROOT = 'C:/Users/cain/Desktop/cmp/static/'
MEDIA_ROOT = 'C:/Users/cain/Desktop/cmp/media/'
# STATIC_ROOT = '/home/qgu/cmp/static/'
# MEDIA_ROOT = '/home/qgu/cmp/media/'
TINYMCE_JS_URL = MEDIA_URL + '/static/tiny_mce/tiny_mce_src.js'

TINYMCE_JS_ROOT = MEDIA_ROOT + '/static/tiny_mce/'