from django.conf.urls import include, url
from campaigns.testticai import views_action_admin, views_page, views_action

urlpatterns = [
        url(r'^back/puv', views_action_admin._PUv),
        url(r'^back/login', views_action_admin.AdminLogIn),
        url(r'^back/priceInfo', views_action_admin.priceInfo),
        url(r'^back/FPriz', views_action_admin.fetchPriz),
        url(r'^back/opload', views_action_admin.upload),
        url(r'^back/startAdd', views_action_admin.startAdd),
        url(r'^back/CountCode', views_action_admin.fetchCode),
        url(r'^back/activedata', views_action_admin.ActiveData),
        url(r'^back/fetchCount$', views_action_admin.fetchCount),
        url(r'^back/userdata', views_action_admin.UserData),
        url(r'^back/sendPrize', views_action_admin.sendPrize),
        url(r'^back/makeWeek', views_action_admin.makeWeek),
        url(r'^back/accessToken', views_action_admin.accessWeek),
        url(r'^back/swprices', views_action_admin.SWPrices),
        url(r'^back/signup', views_action_admin.SignUp),
        url(r'^back/suchactive$', views_action_admin.SuchActive),
        url(r'^back/suchuser$', views_action_admin.SuchUser),
        url(r'^back/suchsign$', views_action_admin.SuchSign),
        url(r'^back/dayCount$', views_action_admin.dayCount),
        url(r'^back/change$', views_action_admin.ChangeCount),
        url(r'^back/fetchDay$', views_action_admin.fetchDay),
        url(r'^main$', views_action.Main),
        url(r'^getCache$', views_action.getCache),
        url(r'^myDonate$', views_action. myDonate),
        url(r'^priCount$', views_action.PriCount),
        url(r'^update', views_action.update),
        url(r'^fetch', views_action.fetchwork),
        url(r'^checkfirst$', views_action.checktoday),
        url(r'^suchAll$', views_action.suchAll),
        url(r'^workcount', views_action.weekCount),
        url(r'^getprice$', views_action.fetchprice),
        url(r'^signin$', views_action.signup),
        url(r'^usrprices$', views_action.usrprices),
        url(r'^activeusr$', views_action.activeuser),
        url(r'^about.html$', views_page.about),
        url(r'^index$', views_page.index),
        url(r'^main/index.html$', views_page.index),
        url(r'^shareIndex$', views_page.shareIndex),
        url(r"^success$", views_page.success),
        url(r'^vsupload$', views_page.vsupload),
        url(r'^get_sign_package', views_action.get_sign_package),
        url(r'^tocloud', views_action.tocloud),
        url(r'^back/index.html$', views_page.backIndex),
        url(r'^back/viste.html$', views_page.backLogin)
        ]
